### PR TITLE
DO NOT MERGE:  config for silk profiling

### PR DESCRIPTION
**Pull request by asamolion**
Use `django-silk==1.0.0`

### CODE REVIEW

**Comment by ahmed-faraz46** [comment]
@asamolion, are you sure you want to merge it in `master`?

**Comment by danialmalik** [comment]
@ahmed-faraz46 this PR is for the reference purpose only. Therefore it is mentioned in the PR name to not to merge i.e. "DO NOT MERGE"

**Comment by ahmed-faraz46** [comment]
@danialmalik thanks for the clarification.

**Comment by imhassantariq** [comment]
Run Migrations after installing silk

`python manage.py lms migrate --settings=devstack`

**Comment by danialmalik** [comment]
@ahmed-faraz46 sure. Saving this link for future references.

**Pull request closed without merging**
