### PR TITLE
LP-2303 LP-2294 Autoscore ORA command with linting and unit test

### PR DESCRIPTION
**Pull request by zahid-arbisoft**
### Description

**[LP-2303](https://philanthropyu.atlassian.net/browse/LP-2303)** Autoscore ORA command (Unit test only)
**[LP-2294](https://philanthropyu.atlassian.net/browse/LP-2294)** Fix all linting errors for assessment

**Notes**

- [x] All unit test included
- [x] Linting issues fixed for open assessment app and command code
- [x] iSort ran on open assessment app and command code

### CODE REVIEW

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by harris-irfan — APPROVED** [review]

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by qasimgulzar — APPROVED** [review]
LGTM

**Comment by ahmed-faraz46** [comment]
jenkins run all

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by zahid-arbisoft** [comment]
jenkins run all

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Pull request merged**
