### PR TITLE
LP-2325 Remove App Usage

### PR DESCRIPTION
**Pull request by abdullah998**
### Description

[LP-2325](https://philanthropyu.atlassian.net/browse/LP-2325)

### CODE REVIEW

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by zahid-arbisoft — APPROVED** [review]
Though code is commented at two places, but since PR was approved for development, approving it master as well.

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by ahmed-faraz46 — APPROVED** [review]

**Comment by ahmed-faraz46** [comment]
> Though code is commented at two places, but since PR was approved for development, approving it master as well.

Yes in next iteration the whole app is to be removed.

**Pull request merged**
