### PR TITLE
LP-2295 Fix Linting For Custom_Fields

### PR DESCRIPTION
**Pull request by abdullah998**
### Description

[LP-2295](https://philanthropyu.atlassian.net/browse/LP-2295)

### CODE REVIEW

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by zahid-arbisoft — APPROVED** [review]

**Review by harris-irfan — APPROVED** [review]

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by emraan004 — APPROVED** [review]

**Pull request merged**
