### PR TITLE
LP-1296 Notification icon count bug at LMS

### PR DESCRIPTION
**Pull request by aliassad**
### Description

[LP-1296](https://philanthropyu.atlassian.net/browse/LP-1296)

When notifications counts exceeds 99 then it should be displayed 99+ at LMS side too.

### CODE REVIEW

**Review by harris-irfan — CHANGES_REQUESTED** [review]
Why are there so many file changes related to tests and testing environment? Are they in the scope of this ticket? There are a total of 15 file changes. Please look into it and remove the extra files from the commit.

**Comment by aliassad** [comment]
> Why are there so many file changes related to tests and testing environment? Are they in the scope of this ticket? There are a total of 15 file changes. Please look into it and remove the extra files from the commit.

@harris-irfan this PR just have one file change which is in View file only , other file changes are due to master verified commit,  i this case you need to ignore the verified commit files.

Go to commit tab  a review only non-verified commits.

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by ahmed-faraz46 — APPROVED** [review]
LGTM 👍 Please make revert PR for your previously merged PRs.

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by harris-irfan — APPROVED** [review]

**Review by zeshanarifios — APPROVED** [review]
LGTM 👍

**Pull request merged**
