### PR TITLE
LP-2245 Write unit tests for notify_non_active_users philu_command

### PR DESCRIPTION
**Pull request by muak50**
### Description

[LP-2245](https://philanthropyu.atlassian.net/browse/LP-2245)

### CODE REVIEW

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by harris-irfan — CHANGES_REQUESTED** [review]

**Review by harris-irfan — APPROVED** [review]
👍

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by qasimgulzar — APPROVED** [review]
LGTM

**Pull request merged**
