### PR TITLE
LP-2272 Fix all linting issues of philu commands

### PR DESCRIPTION
**Pull request by zahid-arbisoft**
### Description

[LP-2272](https://philanthropyu.atlassian.net/browse/LP-2272) Fix all linting issues of philu commands

### Notes

- All linitng issues fixed
- Failing unit test fixed

### CODE REVIEW

**Review by muak50 — CHANGES_REQUESTED** [review]
Few minor suggestions. Rest LGTM 👍

**Review by muak50 — APPROVED** [review]
LGTM 👍

**Comment by zahid-arbisoft** [comment]
> **pylint:** ✔️
> **pycodestyle:** ✔️
> **iSort:** ❌
> 
> ```
> Pylint score
> ------------------------------------
> Your code has been rated at 10.00/10
> ```
> 
> **Please fix following iSort issues:**
> 
> ```
>  ERROR: /home/runner/work/edx-platform/edx-platform/common/djangoapps/philu_commands/management/commands/tests/test_sync_users_with_nodebb_command.py Imports are incorrectly sorted. 
> ```

Isort on local does not flag any issue in imports, not sure why it is showing this error

**Review by ahmed-faraz46 — APPROVED** [review]
Great work @zahid-arbisoft 👏 approving with a few optional suggestions

**Pull request merged**
