### PR TITLE
Integrate action planning tool xblock.

### PR DESCRIPTION
**Pull request by qasimgulzar**
### Description

[LP-2392](https://philanthropyu.atlassian.net/browse/LP-2392)

### CODE REVIEW

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by emraan004 — APPROVED** [review]
LGTM 👍

**Review by zeshanarifios — APPROVED** [review]
LGTM 👍

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Pull request merged**
