### PR TITLE
 LP-2155 Add is_mini_lesson method to add mini lesson header on course card

### PR DESCRIPTION
**Pull request by zeshanarifios**
### Description

[LP-2155](https://philanthropyu.atlassian.net/browse/LP-2155)

[Theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1419)

- [x] Add manager for custom settings
- [x] Add is_mini_lesson method in manager to check if course of given course key is mini lesson or no

### CODE REVIEW

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by ahmed-faraz46 — APPROVED** [review]
LGTM 👍 Would you please have a look at [this ticket](https://philanthropyu.atlassian.net/browse/LP-2316), we fetched is_mini_lesson manually from custom settings, But we can utilize this manager at all those places as well.

**Comment by zeshanarifios** [comment]
> LGTM 👍 Would you please have a look at [this ticket](https://philanthropyu.atlassian.net/browse/LP-2316), we fetched is_mini_lesson manually from custom settings, But we can utilize this manager at all those places as well.

Thank You, 
I looked into that PR. there could be 2 improvements. Instead of using helper methods we can move them to more appropriate places like Manager and Model

1:  `get_course_custom_settings` can be moved inside CustomSettings manager ..
2:  `initialize_course_settings` can be moved in CustomSettings model as static method.

**Review by muak50 — APPROVED** [review]
Just 1 minor doc-string issue, rest LGTM 👍

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Pull request merged**
