### PR TITLE
LP-2400: Fixing site configuration variable issue

### PR DESCRIPTION
**Pull request by zahid-arbisoft**
### Description

[LP-2400](https://philanthropyu.atlassian.net/browse/LP-2400)

### CODE REVIEW

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by ahmed-faraz46 — APPROVED** [review]
LGTM 👍

**Comment by ahmed-faraz46** [comment]
@zahid-arbisoft there is some issue in isort, please have a look.

**Review by muak50 — APPROVED** [review]
LGTM 👍

**Comment by zahid-arbisoft** [comment]
@ahmed-faraz46 About iSort I have left a [comment on channel](https://arbisoft.slack.com/archives/CGYKGH4P5/p1601976401016600). I think we need to recheck iSort job.

**Pull request merged**
