### PR TITLE
LP-2284 Fix all linting errors for job_board

### PR DESCRIPTION
**Pull request by harris-irfan**
### Description

[LP-2284](https://philanthropyu.atlassian.net/browse/LP-2284)

### Notes

- [x] Fix all linting errors in Job Board app

- [x] Run isort on all files in Job Board app

- [x] Make sure all unit tests are passing

Pylint report:
-------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 9.81/10, +0.19)

**Note:** In the second commit, by mistake the commit message states 'LP-2288'. It is actually meant to be 'LP-2284'.

### CODE REVIEW

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Review by zahid-arbisoft — APPROVED** [review]
Can you remove `tests/view` folder and rename `tests/views/test_job_board.py` to `tests/test_views.py`, for consistancy.

PR looks good 👍

**Review by saad-waqar — APPROVED** [review]

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by philanthropyu** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Pull request merged**
