### PR TITLE
LP-2452 :bug: User is unable to get specialisation certificate.

### PR DESCRIPTION
**Pull request by qasimgulzar**
### Description

[LP-2452](https://philanthropyu.atlassian.net/browse/LP-2452)

Added some logging and fix for backword compatibility.

### CODE REVIEW

**Comment by qasimgulzar** [comment]
> **pylint:** ❌
> **pycodestyle:** ❌
> **iSort:** ❌
> 
> **Please fix following pylint issues:**
> 
> ```
> ************* Module edx-platform.openedx.core.djangoapps.certificates.api
> C:100, 0: Line too long (159/120) (line-too-long)
> C: 59, 0: Missing function docstring (missing-docstring)
> C: 98, 0: Missing function docstring (missing-docstring)
> C:106, 0: Missing function docstring (missing-docstring)
> ************* Module edx-platform.openedx.core.djangoapps.programs.utils
> C:333, 0: Line too long (128/120) (line-too-long)
> C:337, 0: Line too long (140/120) (line-too-long)
> W:295,12: Specify string format arguments as logging function parameters (logging-not-lazy)
> W:320,16: Specify string format arguments as logging function parameters (logging-not-lazy)
> C:330,38: Comparison to None should be 'expr is None' (singleton-comparison)
> R:657, 8: Too many nested blocks (6/5) (too-many-nested-blocks)
> R:644, 4: Too many statements (54/50) (too-many-statements)
> 
> -----------------------------------
> Your code has been rated at 9.76/10
> ```
> 
> **Please fix following pycodestyle issues:**
> 
> ```
>  openedx/core/djangoapps/programs/utils.py:330:58: E711 comparison to None should be 'if cond is None:' 
> ```
> 
> **Please fix following iSort issues:**
> 
> ```
>  ERROR: /home/runner/work/edx-platform/edx-platform/openedx/core/djangoapps/programs/utils.py Imports are incorrectly sorted. 
> ```

Working on it

**Review by zahid-arbisoft — APPROVED** [review]
LGTM.

Please log core changes, if not already logged

**Comment by qasimgulzar** [comment]
> LGTM.
> 
> Please log core changes, if not already logged

Already logged [here](https://github.com/philanthropy-u/edx-platform/wiki/LP-2452-User-is-unable-to-get-specialisation-certificate.)

**Review by ahmed-faraz46 — APPROVED** [review]
LGTM 👍

**Pull request merged**
